version: "3"

services:
  php:
    image: diovanegabriel/php8.2-cli:latest
    container_name: query-builder-php-test
    command: php -S 0.0.0.0:8080 -t /var/www/html
    volumes:
      - ./:/var/www/html
    # network_mode: "host"
    networks:
      - custom_network

networks:
  custom_network:
    external: true